#### Minimum usage of this module : 
Import extraction, transformation and loading modules. Fatch data (ademe + enedis) - transform and select columns according to a schema - upload data into database

In [ ]:
# utilisation locale après avoir git clone ce projet
# %pip install --force-reinstall --no-cache --no-deps -e "DPE-Energy-Performance-Analysis-ETL"

# utilisation du package depuis pypi.org (dernière version publiée)
%pip install dpe_enedis_ademe_etl_engine

Obtaining file:///Users/fereolgbenou/Desktop/projets_data/DPE-Energy-Performance-Analysis/DPE-Energy-Performance-Analysis-ETL
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: dpe_enedis_ademe_etl_engine
  Building editable for dpe_enedis_ademe_etl_engine (pyproject.toml) ... done
  Created wheel for dpe_enedis_ademe_etl_engine: filename=dpe_enedis_ademe_etl_engine-2.3.1-0.editable-py3-none-any.whl size=10122 sha256=a57c3bbb45f41a9e106bc6eb60a80e1f466ff876499427eb766f2d2dc4fe4af8
  Stored in directory: /private/var/folders/4f/_8hmn59n45x585yn7s70dhww0000gn/T/pip-ephem-wheel-cache-8my9es0c/wheels/eb/55/cf/1fcd9a1761c48332e97ac9f58429bb697ecf1f342df51cc281
Successfully built dpe_enedis_ademe_etl_engine
Installing collected packages: dpe_enedis_ademe_etl_engine
  Attempting uninstall: dpe_enedis_ademe_etl_engine
    Found existing installation: dpe_enedis_ademe_etl_engine 2.2.10
    Uninstalling dpe_enedis_ademe_etl_engine-2.2.10:
      Successfully uninstalled dpe_enedis_ademe_etl_engine-2.2.10
Successfully installed dpe_enedis_ademe_etl_engine-2.3.1

[notice] A new release of pip is available: 24.3.1 -> 26.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip show dpe_enedis_ademe_etl_engine
# redemarrer le noyau ici

Name: dpe_enedis_ademe_etl_engine
Version: 2.3.1
Summary: Dataflows (ETL) backend for DPE Energy Performance Analysis.
Home-page:
Author:
Author-email: Féréol Gbenou <fereol.gbenou@ynov.com>
License:
Location: /Users/fereolgbenou/Desktop/projets_data/DPE-Energy-Performance-Analysis/venv/lib/python3.12/site-packages
Editable project location: /Users/fereolgbenou/Desktop/projets_data/DPE-Energy-Performance-Analysis/DPE-Energy-Performance-Analysis-ETL
Requires: boto3, click, fastapi, httpx, minio, numpy, pandas, pathlib, prefect, prometheus-client, psutil, psycopg2-binary, pyarrow, pydantic, pyjwt, pytest, python-multipart, pyyaml, redis, Requests, scikit-learn, slowapi, SQLAlchemy, sqlalchemy, unidecode, uvicorn, yappi
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# pas obligatoire, si non est géré automatiquement par le package lors de l'import
import os, uuid
os.environ["BATCH_CORRELATION_ID"] = str(uuid.uuid4()).replace("-", "")
print(os.environ["BATCH_CORRELATION_ID"])

b77bdaf8ac6742e2963f8700da74aad0

In [ ]:
dict_config = {
    "ENV": "LOCAL", # LOCAL | NOLOCAL | ISOLATED

    # (pas obligatoire) exemple de config pour la connexion à un serveur postgres distant 
    "POSTGRES_HOST": "192.168.137.1",
    "POSTGRES_PORT": "5432",
    "POSTGRES_DB_NAME": "dpedb_v1_domestic_remote",
    "POSTGRES_ADMIN_USERNAME": "postgres",
    "POSTGRES_ADMIN_PASSWORD": "azertyuiop23", 

}

import os, uuid
for key, value in dict_config.items():
    os.environ[key] = value

In [ ]:
from dpe_enedis_ademe_etl_engine.pipelines import DataEnedisAdemeExtractor

pipeline = DataEnedisAdemeExtractor()

os.environ['PREFECT_API_URL'] = ''
pipeline.extract.fn(
    pipeline,
    from_input=False, 
    code_departement=78,  
    annee=2023, 
    rows=10, 
    n_threads_for_querying=5
    )

2026-02-03 12:12:47,678 - root - WARNING - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger
2026-02-03 12:12:47,679 - root - WARNING - Environment variable PATH_LOG_DIR is not set, and is not compulsory, default value is : None
2026-02-03 12:12:47,679 - root - WARNING - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger
2026-02-03 12:12:47,679 - root - WARNING - Environment variable PATH_LOG_DIR is not set, and is not compulsory, default value is : None
2026-02-03 12:12:47,679 - root - WARNING - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger
2026-02-03 12:12:47,680 - root - WARNING - Environment variable PATH_LOG_DIR is not set, and is not compulsory, default value is : None
2026-02-03 12:12:47,680 - root - WARNING - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger
2026-02-03 12:12:47,680 - root - WARNING - Environment variable PATH_LOG_DIR is not set, and is not compulsory, default value is : None
2026-02-03 12:12:47,680 - root - WARNING - Loading envs var from folder : /Users/fereolgbenou/Desktop/projets_data/DPE-Energy-Performance-Analysis/DPE-Energy-Performance-Analysis-ETL/src/dpe_enedis_ademe_etl_engine/config
2026-02-03 12:12:47,681 - root - INFO - Application None is running on env None

Loading environment variables from /Users/fereolgbenou/Desktop/projets_data/DPE-Energy-Performance-Analysis/config/.env ...
2026-02-03 12:12:50,853 - dpe_ETL_engine_logger - INFO - Environment: LOCAL - ENV:LOCAL
2026-02-03 12:12:50,853 - dpe_ETL_engine_logger - INFO - Environment: LOCAL - ENV:LOCAL
2026-02-03 12:12:50,853 - dpe_ETL_engine_logger - INFO - Environment: LOCAL - ENV:LOCAL
2026-02-03 12:12:50,853 - dpe_ETL_engine_logger - INFO - Environment: LOCAL - ENV:LOCAL
2026-02-03 12:12:50,900 - dpe_ETL_engine_logger - INFO - Fetching data from : https://opendata.enedis.fr/data-fair/api/v1/datasets/consommation-annuelle-residentielle-par-adresse/lines?annee_eq=2023&size=10&code_departement%3D78 - ENV:LOCAL
2026-02-03 12:12:50,900 - dpe_ETL_engine_logger - INFO - Fetching data from : https://opendata.enedis.fr/data-fair/api/v1/datasets/consommation-annuelle-residentielle-par-adresse/lines?annee_eq=2023&size=10&code_departement%3D78 - ENV:LOCAL
2026-02-03 12:12:50,900 - dpe_ETL_engine_logger - INFO - Fetching data from : https://opendata.enedis.fr/data-fair/api/v1/datasets/consommation-annuelle-residentielle-par-adresse/lines?annee_eq=2023&size=10&code_departement%3D78 - ENV:LOCAL
2026-02-03 12:12:50,900 - dpe_ETL_engine_logger - INFO - Fetching data from : https://opendata.enedis.fr/data-fair/api/v1/datasets/consommation-annuelle-residentielle-par-adresse/lines?annee_eq=2023&size=10&code_departement%3D78 - ENV:LOCAL

12:12:51.153 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

2026-02-03 12:12:51,156 - dpe_ETL_engine_logger - INFO - Extract input from url enedis :
 https://opendata.enedis.fr/data-fair/api/v1/datasets/consommation-annuelle-residentielle-par-adresse/lines?annee_eq=2023&size=10&code_departement%3D78 - ENV:LOCAL
2026-02-03 12:12:51,156 - dpe_ETL_engine_logger - INFO - Extract input from url enedis :
 https://opendata.enedis.fr/data-fair/api/v1/datasets/consommation-annuelle-residentielle-par-adresse/lines?annee_eq=2023&size=10&code_departement%3D78 - ENV:LOCAL
2026-02-03 12:12:51,156 - dpe_ETL_engine_logger - INFO - Extract input from url enedis :
 https://opendata.enedis.fr/data-fair/api/v1/datasets/consommation-annuelle-residentielle-par-adresse/lines?annee_eq=2023&size=10&code_departement%3D78 - ENV:LOCAL
2026-02-03 12:12:51,156 - dpe_ETL_engine_logger - INFO - Extract input from url enedis :
 https://opendata.enedis.fr/data-fair/api/v1/datasets/consommation-annuelle-residentielle-par-adresse/lines?annee_eq=2023&size=10&code_departement%3D78 - ENV:LOCAL
2026-02-03 12:12:51,156 - dpe_ETL_engine_logger - INFO - Shape of raw loaded dataframe : (10, 22) with cols ['consommation_annuelle_moyenne_de_la_commune_mwh', 'code_departement', 'nom_iris', 'numero_de_voie', '_i', 'annee', 'code_iris', 'code_commune', 'type_de_voie', 'nombre_de_logements', 'code_epci', 'tri_des_adresses', 'libelle_de_voie', 'segment_de_client', '_rand', 'code_region', 'adresse', 'nom_commune', 'consommation_annuelle_moyenne_par_site_de_ladresse_mwh', 'consommation_annuelle_totale_de_ladresse_mwh', '_score', '_id'] - ENV:LOCAL
2026-02-03 12:12:51,156 - dpe_ETL_engine_logger - INFO - Shape of raw loaded dataframe : (10, 22) with cols ['consommation_annuelle_moyenne_de_la_commune_mwh', 'code_departement', 'nom_iris', 'numero_de_voie', '_i', 'annee', 'code_iris', 'code_commune', 'type_de_voie', 'nombre_de_logements', 'code_epci', 'tri_des_adresses', 'libelle_de_voie', 'segment_de_client', '_rand', 'code_region', 'adresse', 'nom_commune', 'consommation_annuelle_moyenne_par_site_de_ladresse_mwh', 'consommation_annuelle_totale_de_ladresse_mwh', '_score', '_id'] - ENV:LOCAL
2026-02-03 12:12:51,156 - dpe_ETL_engine_logger - INFO - Shape of raw loaded dataframe : (10, 22) with cols ['consommation_annuelle_moyenne_de_la_commune_mwh', 'code_departement', 'nom_iris', 'numero_de_voie', '_i', 'annee', 'code_iris', 'code_commune', 'type_de_voie', 'nombre_de_logements', 'code_epci', 'tri_des_adresses', 'libelle_de_voie', 'segment_de_client', '_rand', 'code_region', 'adresse', 'nom_commune', 'consommation_annuelle_moyenne_par_site_de_ladresse_mwh', 'consommation_annuelle_totale_de_ladresse_mwh', '_score', '_id'] - ENV:LOCAL
2026-02-03 12:12:51,156 - dpe_ETL_engine_logger - INFO - Shape of raw loaded dataframe : (10, 22) with cols ['consommation_annuelle_moyenne_de_la_commune_mwh', 'code_departement', 'nom_iris', 'numero_de_voie', '_i', 'annee', 'code_iris', 'code_commune', 'type_de_voie', 'nombre_de_logements', 'code_epci', 'tri_des_adresses', 'libelle_de_voie', 'segment_de_client', '_rand', 'code_region', 'adresse', 'nom_commune', 'consommation_annuelle_moyenne_par_site_de_ladresse_mwh', 'consommation_annuelle_totale_de_ladresse_mwh', '_score', '_id'] - ENV:LOCAL

12:12:51.180 | INFO    | Task run 'validate-enedis-input-df-schema' - Finished in state Completed()

12:12:51.182 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

12:12:51.209 | INFO    | Task run 'compute-adress-columns-and-format' - Finished in state Completed()

12:12:51.210 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

2026-02-03 12:12:51,210 - dpe_ETL_engine_logger - INFO - Shape of loaded dataframe : (10, 23) with cols ['consommation_annuelle_moyenne_de_la_commune_mwh', 'code_departement', 'nom_iris', 'numero_de_voie', '_i', 'annee', 'code_iris', 'code_commune', 'type_de_voie', 'nombre_de_logements', 'code_epci', 'tri_des_adresses', 'libelle_de_voie', 'segment_de_client', '_rand', 'code_region', 'adresse', 'nom_commune', 'consommation_annuelle_moyenne_par_site_de_ladresse_mwh', 'consommation_annuelle_totale_de_ladresse_mwh', '_score', '_id', 'full_adress'] - ENV:LOCAL
2026-02-03 12:12:51,210 - dpe_ETL_engine_logger - INFO - Shape of loaded dataframe : (10, 23) with cols ['consommation_annuelle_moyenne_de_la_commune_mwh', 'code_departement', 'nom_iris', 'numero_de_voie', '_i', 'annee', 'code_iris', 'code_commune', 'type_de_voie', 'nombre_de_logements', 'code_epci', 'tri_des_adresses', 'libelle_de_voie', 'segment_de_client', '_rand', 'code_region', 'adresse', 'nom_commune', 'consommation_annuelle_moyenne_par_site_de_ladresse_mwh', 'consommation_annuelle_totale_de_ladresse_mwh', '_score', '_id', 'full_adress'] - ENV:LOCAL
2026-02-03 12:12:51,210 - dpe_ETL_engine_logger - INFO - Shape of loaded dataframe : (10, 23) with cols ['consommation_annuelle_moyenne_de_la_commune_mwh', 'code_departement', 'nom_iris', 'numero_de_voie', '_i', 'annee', 'code_iris', 'code_commune', 'type_de_voie', 'nombre_de_logements', 'code_epci', 'tri_des_adresses', 'libelle_de_voie', 'segment_de_client', '_rand', 'code_region', 'adresse', 'nom_commune', 'consommation_annuelle_moyenne_par_site_de_ladresse_mwh', 'consommation_annuelle_totale_de_ladresse_mwh', '_score', '_id', 'full_adress'] - ENV:LOCAL
2026-02-03 12:12:51,210 - dpe_ETL_engine_logger - INFO - Shape of loaded dataframe : (10, 23) with cols ['consommation_annuelle_moyenne_de_la_commune_mwh', 'code_departement', 'nom_iris', 'numero_de_voie', '_i', 'annee', 'code_iris', 'code_commune', 'type_de_voie', 'nombre_de_logements', 'code_epci', 'tri_des_adresses', 'libelle_de_voie', 'segment_de_client', '_rand', 'code_region', 'adresse', 'nom_commune', 'consommation_annuelle_moyenne_par_site_de_ladresse_mwh', 'consommation_annuelle_totale_de_ladresse_mwh', '_score', '_id', 'full_adress'] - ENV:LOCAL

12:12:51.211 | INFO    | Task run 'extract-data-from-enedis-api' - Finished in state Completed()

12:12:51.212 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

12:12:51.227 | WARNING | prefect.events.clients - Unable to connect to 'wss://api.prefect.cloud/api/accounts/cabcaeeb-e409-465b-8ca4-eee7acbfb21f/workspaces/2e0b4380-5c9b-49eb-a038-a4df74e3082c/events/in'. Please check your network settings to ensure websocket connections to the API are allowed. Otherwise event data (including task run data) may be lost. Reason: server rejected WebSocket connection: HTTP 401. Set PREFECT_DEBUG_MODE=1 to see the full error.

12:12:51.228 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 9 pending items.

12:12:51.540 | WARNING | prefect.events.clients - Unable to connect to 'wss://api.prefect.cloud/api/accounts/cabcaeeb-e409-465b-8ca4-eee7acbfb21f/workspaces/2e0b4380-5c9b-49eb-a038-a4df74e3082c/events/in'. Please check your network settings to ensure websocket connections to the API are allowed. Otherwise event data (including task run data) may be lost. Reason: server rejected WebSocket connection: HTTP 401. Set PREFECT_DEBUG_MODE=1 to see the full error.

12:12:51.543 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 2 pending items.
--- Error logging to API ---
Client error '401 Unauthorized' for url 'https://api.prefect.cloud/api/accounts/cabcaeeb-e409-465b-8ca4-eee7acbfb21f/workspaces/2e0b4380-5c9b-49eb-a038-a4df74e3082c/logs/'
Response: {'detail': 'Unauthorized'}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2026-02-03 12:12:53,761 - dpe_ETL_engine_logger - INFO - Valid data BAN : 10 addresses founded over 10 requested. - ENV:LOCAL
2026-02-03 12:12:53,761 - dpe_ETL_engine_logger - INFO - Valid data BAN : 10 addresses founded over 10 requested. - ENV:LOCAL
2026-02-03 12:12:53,761 - dpe_ETL_engine_logger - INFO - Valid data BAN : 10 addresses founded over 10 requested. - ENV:LOCAL
2026-02-03 12:12:53,761 - dpe_ETL_engine_logger - INFO - Valid data BAN : 10 addresses founded over 10 requested. - ENV:LOCAL

12:12:53.765 | INFO    | Task run 'extract-data-from-ban-api' - Finished in state Completed()

12:12:53.766 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

12:12:53.863 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

12:12:53.864 | INFO    | Task run 'join-enedis-data-with-ban-data' - Finished in state Completed()

12:12:53.865 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

12:12:54.057 | WARNING | prefect.events.clients - Unable to connect to 'wss://api.prefect.cloud/api/accounts/cabcaeeb-e409-465b-8ca4-eee7acbfb21f/workspaces/2e0b4380-5c9b-49eb-a038-a4df74e3082c/events/in'. Please check your network settings to ensure websocket connections to the API are allowed. Otherwise event data (including task run data) may be lost. Reason: server rejected WebSocket connection: HTTP 401. Set PREFECT_DEBUG_MODE=1 to see the full error.

12:12:54.058 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 6 pending items.
--- Error logging to API ---
Client error '401 Unauthorized' for url 'https://api.prefect.cloud/api/accounts/cabcaeeb-e409-465b-8ca4-eee7acbfb21f/workspaces/2e0b4380-5c9b-49eb-a038-a4df74e3082c/logs/'
Response: {'detail': 'Unauthorized'}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

12:13:06.258 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

12:13:06.260 | INFO    | Task run 'extract-data-from-ademe-api' - Finished in state Completed()

12:13:06.260 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

12:13:06.425 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

2026-02-03 12:13:06,425 - dpe_ETL_engine_logger - INFO - Enedis with BAN data loaded : 10 rows, 43 columns. - ENV:LOCAL
2026-02-03 12:13:06,425 - dpe_ETL_engine_logger - INFO - Enedis with BAN data loaded : 10 rows, 43 columns. - ENV:LOCAL
2026-02-03 12:13:06,425 - dpe_ETL_engine_logger - INFO - Enedis with BAN data loaded : 10 rows, 43 columns. - ENV:LOCAL
2026-02-03 12:13:06,425 - dpe_ETL_engine_logger - INFO - Enedis with BAN data loaded : 10 rows, 43 columns. - ENV:LOCAL
2026-02-03 12:13:06,425 - dpe_ETL_engine_logger - INFO - Ademe data loaded : 50 rows, 178 columns. - ENV:LOCAL
2026-02-03 12:13:06,425 - dpe_ETL_engine_logger - INFO - Ademe data loaded : 50 rows, 178 columns. - ENV:LOCAL
2026-02-03 12:13:06,425 - dpe_ETL_engine_logger - INFO - Ademe data loaded : 50 rows, 178 columns. - ENV:LOCAL
2026-02-03 12:13:06,425 - dpe_ETL_engine_logger - INFO - Ademe data loaded : 50 rows, 178 columns. - ENV:LOCAL

12:13:06.448 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

12:13:06.450 | INFO    | Task run 'join-all-and-backup' - Finished in state Completed()

12:13:06.451 | WARNING | root - Environment variable ETL_LOGGER_APP_NAME is not set, using default value: dpe_ETL_engine_logger

2026-02-03 12:13:06,452 - dpe_ETL_engine_logger - INFO - Extraction results : 50 rows, 222 columns. - ENV:LOCAL
2026-02-03 12:13:06,452 - dpe_ETL_engine_logger - INFO - Extraction results : 50 rows, 222 columns. - ENV:LOCAL
2026-02-03 12:13:06,452 - dpe_ETL_engine_logger - INFO - Extraction results : 50 rows, 222 columns. - ENV:LOCAL
2026-02-03 12:13:06,452 - dpe_ETL_engine_logger - INFO - Extraction results : 50 rows, 222 columns. - ENV:LOCAL
2026-02-03 12:13:06,453 - dpe_ETL_engine_logger - INFO - Extraction schema saved in : config/schema_silver_data.json - ENV:LOCAL
2026-02-03 12:13:06,453 - dpe_ETL_engine_logger - INFO - Extraction schema saved in : config/schema_silver_data.json - ENV:LOCAL
2026-02-03 12:13:06,453 - dpe_ETL_engine_logger - INFO - Extraction schema saved in : config/schema_silver_data.json - ENV:LOCAL
2026-02-03 12:13:06,453 - dpe_ETL_engine_logger - INFO - Extraction schema saved in : config/schema_silver_data.json - ENV:LOCAL

12:13:06.589 | WARNING | prefect.events.clients - Unable to connect to 'wss://api.prefect.cloud/api/accounts/cabcaeeb-e409-465b-8ca4-eee7acbfb21f/workspaces/2e0b4380-5c9b-49eb-a038-a4df74e3082c/events/in'. Please check your network settings to ensure websocket connections to the API are allowed. Otherwise event data (including task run data) may be lost. Reason: server rejected WebSocket connection: HTTP 401. Set PREFECT_DEBUG_MODE=1 to see the full error.

12:13:06.590 | ERROR   | GlobalEventLoopThread | prefect._internal.concurrency - Service 'EventsWorker' failed with 4 pending items.
--- Error logging to API ---
Client error '401 Unauthorized' for url 'https://api.prefect.cloud/api/accounts/cabcaeeb-e409-465b-8ca4-eee7acbfb21f/workspaces/2e0b4380-5c9b-49eb-a038-a4df74e3082c/logs/'
Response: {'detail': 'Unauthorized'}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

In [3]:
pipeline.output.batch_id.value_counts()

batch_id
012a80ce1dc84680851f271bed1b7bb1    50
Name: count, dtype: int64

In [ ]:
# save above results into a db - files are already saved in the path set in env vars
import pandas as pd
from sqlalchemy import create_engine

uri = f"postgresql://{os.environ['POSTGRES_ADMIN_USERNAME']}:{os.environ['POSTGRES_ADMIN_PASSWORD']}@{os.environ['POSTGRES_HOST']}:{os.environ['POSTGRES_PORT']}/{os.environ['POSTGRES_DB_NAME']}"
obj_engine = create_engine(uri)
pipeline.output.to_sql(
    "raw_extract",
    con=obj_engine,
    if_exists="append",
    index=False
)

pd.read_sql("select * from raw_extract limit 10", con=obj_engine)

,_geopoint_ademe,_i_ademe,_id_ademe,_rand_ademe,_score_ademe,_type_ban,adresse_ban_ademe,adresse_brut_ademe,adresse_enedis,annee_construction_ademe,...,usage_generateur_n1_installation_n1_ademe,usage_generateur_n1_installation_n2_ademe,usage_generateur_n2_installation_n1_ademe,ventilation_posterieure_2012_ademe,version_dpe_ademe,volume_stockage_generateur_n1_ecs_n1_ademe,x_ban,y_ban,zone_climatique_ademe,batch_id
0,"48.988009959973944,2.2579859433629488",1418882037897,badc4a51232b097d77f1f20f1cd62defbc24e8c233dfe0...,86095,54.246910,address,23 Rue de Stalingrad 95120 Ermont,23 Rue de Stalingrad,23 RUE DE STALINGRAD,2010.0,...,None,None,None,0,1.0,NaN,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee
1,"48.988009959973944,2.2579859433629488",1431404400434,f46a381a43ee70da6d0f0e2bbc9c7bd1a7178d8b4b031a...,16680,54.246910,address,23 Rue de Stalingrad 95120 Ermont,23 Rue de Stalingrad,23 RUE DE STALINGRAD,2012.0,...,chauffage + ecs,None,None,0,2.0,0.0,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee
2,"48.988009959973944,2.2579859433629488",1432737731202,6e02b9ed661ba4fe76270e38471342ef65b45e09db0a84...,998069,54.246910,address,23 Rue de Stalingrad 95120 Ermont,de Stalingrad,23 RUE DE STALINGRAD,2012.0,...,chauffage + ecs,None,None,0,2.1,0.0,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee
3,"48.988009959973944,2.2579859433629488",1506896546455,d1d48f6567a00be42c897f7f5b3063abba587fe24a2165...,138883,54.246910,address,23 Rue de Stalingrad 95120 Ermont,"23, Rue de Stalingrad - Villa Caroline",23 RUE DE STALINGRAD,NaN,...,chauffage + ecs,None,None,0,2.2,0.0,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee
4,"48.988009959973944,2.2579859433629488",1507166102031,e44cf8a4ab2d029cfbf2aa8394f4a293a5d312b258e5cf...,313663,54.246910,address,23 Rue de Stalingrad 95120 Ermont,23 RUE DE STALINGRAD \n1ER ETAGE BAT B,23 RUE DE STALINGRAD,NaN,...,chauffage + ecs,None,None,0,2.2,0.0,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee
5,"48.988009959973944,2.2579859433629488",1509220240962,6a4614954f3823fe8ce5643b2d90c3ed3de088729afda9...,118882,54.246910,address,23 Rue de Stalingrad 95120 Ermont,23 RUE DE STALINGRAD\nBAT B - RDC - APPT B004,23 RUE DE STALINGRAD,NaN,...,chauffage + ecs,None,None,0,2.2,0.0,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee
6,"48.988009959973944,2.2579859433629488",1509281820597,9a5ffbc0403952c98b5802e7952396d57b638229520494...,412799,54.246910,address,23 Rue de Stalingrad 95120 Ermont,23 RUE DE STALINGRAD\n4EME ETAGE,23 RUE DE STALINGRAD,2012.0,...,chauffage + ecs,None,None,0,2.2,0.0,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee
7,"50.67674701609917,2.8374759998925843",7419655898989,7a5ff3a5a8bd5949ce742d4ccf11acb6f322b4d873e6f9...,680975,58.641357,address,7 Rue des Tisserands 59193 Erquinghem-Lys,des Tisserands,7 RUE DES TISSERANDS,2010.0,...,None,None,None,0,1.0,NaN,688492.00,7064445.26,H1a,d684cd622d204b2daf901cb1adfb73ee
8,"48.988009959973944,2.2579859433629488",1510030387874,29b1c3413413923a572cc0dcda4bbe29cba5c357afdc64...,415189,54.246910,address,23 Rue de Stalingrad 95120 Ermont,23 RUE DE STALINGRAD\n5EME ETAGE - BAT A,23 RUE DE STALINGRAD,2012.0,...,chauffage + ecs,None,None,0,2.2,0.0,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee
9,"48.988009959973944,2.2579859433629488",1525947741462,c743c80e6d5d0fecea18fc0f133b6dffbc737d504a07ef...,36422,54.246910,address,23 Rue de Stalingrad 95120 Ermont,23 RUE DE STALINGRAD,23 RUE DE STALINGRAD,2011.0,...,chauffage + ecs,None,None,0,2.3,0.0,645693.77,6876708.46,H1a,d684cd622d204b2daf901cb1adfb73ee

In [14]:
# transfor and load steps

from dpe_enedis_ademe_etl_engine.pipelines import DataEnedisAdemeTransformer, DataEnedisAdemeLoader


pipeline_transform = DataEnedisAdemeTransformer(
    df=pipeline.output,
    golden_data_config_fpath="z_golden_schema.json"
)
pipeline_transform.run()

Environment: LOCAL

12:13:01.099 | INFO    | Flow run 'gainful-binturong' - Beginning flow run 'gainful-binturong' for flow 'ETL data transformation pipeline'

12:13:01.100 | INFO    | Flow run 'gainful-binturong' - View at http://localhost:4200/runs/flow-run/026475e5-bdf1-46cb-b4e1-e4c45f17f522

12:13:01.161 | INFO    | Task run 'transform-auto-cast-object-variables-0d4' - Finished in state Completed()

12:13:01.183 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column annee_construction_ademe filled with median due to outliers below Q1 - 1.5*IQR.

12:13:01.184 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column appartement_non_visite_ademe filled with mean as no outliers detected.

12:13:01.186 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column apport_interne_saison_chauffe_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.187 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column apport_interne_saison_froide_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.189 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column apport_solaire_saison_chauffe_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.191 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column apport_solaire_saison_froide_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.192 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column besoin_chauffage_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.194 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column besoin_ecs_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.195 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column besoin_refroidissement_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.197 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_5_usages_ef_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.200 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_chauffage_ef_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.202 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_chauffage_generateur_n1_installation_n1_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.203 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_chauffage_generateur_n1_installation_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.204 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_chauffage_generateur_n2_installation_n1_ademe filled with median due to outliers below Q1 - 1.5*IQR.

12:13:01.206 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_chauffage_installation_chauffage_n1_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.207 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_chauffage_installation_chauffage_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.208 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_ecs_ef_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.209 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_ef_generateur_n1_ecs_n1_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.212 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_ef_installation_ecs_n1_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.215 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column conso_refroidissement_annuel_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.216 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column cop_generateur_n1_ecs_n1_ademe filled with mean as no outliers detected.

12:13:01.218 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column cout_chauffage_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.219 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column cout_ecs_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.220 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column cout_total_5_usages_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.222 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column deperditions_baies_vitrees_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.223 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column deperditions_enveloppe_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.227 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column deperditions_murs_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.228 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column deperditions_planchers_bas_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.230 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column deperditions_planchers_hauts_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.231 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column deperditions_ponts_thermiques_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.232 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column deperditions_portes_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.234 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column deperditions_renouvellement_air_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.236 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column electricite_pv_autoconsommee_ademe filled with median due to outliers below Q1 - 1.5*IQR.

12:13:01.239 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column emission_ges_5_usages_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.241 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column emission_ges_chauffage_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.243 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column emission_ges_ecs_energie_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.246 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column facteur_couverture_solaire_n1_ademe filled with mean as no outliers detected.

12:13:01.248 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column inertie_lourde_ademe filled with mean as no outliers detected.

12:13:01.249 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column isolation_toiture_ademe filled with mean as no outliers detected.

12:13:01.250 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column logement_traversant_ademe filled with mean as no outliers detected.

12:13:01.252 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column nombre_appartement_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.253 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column nombre_logements_desservis_par_installation_ecs_n1_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.254 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column nombre_module_ademe filled with mean as no outliers detected.

12:13:01.256 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column nombre_niveau_immeuble_ademe filled with median due to outliers below Q1 - 1.5*IQR.

12:13:01.257 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column nombre_niveau_logement_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.260 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column numero_etage_appartement_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.262 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column numero_rpls_logement_ademe filled with mean as no outliers detected.

12:13:01.264 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column presence_brasseur_air_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.265 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column presence_production_pv_ademe filled with median due to outliers below Q1 - 1.5*IQR.

12:13:01.266 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column production_ecs_solaire_installation_n1_ademe filled with mean as no outliers detected.

12:13:01.267 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column protection_solaire_exterieure_ademe filled with mean as no outliers detected.

12:13:01.269 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column surface_chauffee_installation_chauffage_n1_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.275 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column surface_chauffee_installation_chauffage_n2_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.286 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column surface_climatisee_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.293 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column surface_habitable_desservie_par_installation_ecs_n1_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.298 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column surface_habitable_immeuble_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.300 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column surface_habitable_logement_ademe filled with median due to outliers below Q1 - 1.5*IQR.

12:13:01.301 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column surface_totale_capteurs_pv_ademe filled with mean as no outliers detected.

12:13:01.305 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column surface_ventilee_ademe filled with mean as no outliers detected.

12:13:01.311 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Column volume_stockage_generateur_n1_ecs_n1_ademe filled with median due to outliers above Q3 + 1.5*IQR.

12:13:01.313 | INFO    | Task run 'transform-imputation-with-float-variables-34f' - Finished in state Completed()

12:13:01.330 | INFO    | Task run 'transform-compute-conso-per-kwh-8cd' - Column consommation_annuelle_moyenne_par_site_de_l_adresse_mwh_enedis found. Computing conso_kwh.

12:13:01.332 | INFO    | Task run 'transform-compute-conso-per-kwh-8cd' - Finished in state Completed()

12:13:01.353 | INFO    | Task run 'transform-compute-arrondissement-f4b' - Finished in state Completed()

12:13:01.376 | INFO    | Task run 'transform-compute-conso-per-kwh-per-m2-35b' - Computing conso_kwh_m2 from conso_kwh and surface_habitable_logement_ademe.

12:13:01.378 | INFO    | Task run 'transform-compute-conso-per-kwh-per-m2-35b' - Finished in state Completed()

12:13:01.399 | INFO    | Task run 'transform-compute-absolute-diff-cols-ba3' - Computing absolute_diff_conso_prim_fin, absolute_diff_conso_fin_act, and consumption_difference from conso_5_usages_par_m2_ep_ademe, conso_5_usages_par_m2_ef_ademe, and conso_kwh_m2.

12:13:01.404 | INFO    | Task run 'transform-compute-absolute-diff-cols-ba3' - Finished in state Completed()

12:13:01.427 | INFO    | Task run 'transform-select-and-split-per-entities-f88' - Reading golden data configs from : z_golden_schema.json and currently in /Users/fereolgbenou/Desktop/projets_data/DPE-Energy-Performance-Analysis

12:13:01.435 | INFO    | Task run 'transform-select-and-split-per-entities-f88' - Finished in state Completed()

12:13:01.469 | INFO    | Task run 'transform-make-statistical-metrics-0c4' - [{'etiquette_dpe_ademe': 'A', 'sample_size': 2, 'paired_t_test_t_statistic': np.float64(3.5311520136824535), 'paired_t_test_p_value': np.float64(0.17568653047067995), 'wilcoxon_statistic': np.float64(0.0), 'wilcoxon_p_value': np.float64(0.5)}, {'etiquette_dpe_ademe': 'B', 'sample_size': 3, 'paired_t_test_t_statistic': np.float64(-1.0466131565985144), 'paired_t_test_p_value': np.float64(0.4051220604678294), 'wilcoxon_statistic': np.float64(1.0), 'wilcoxon_p_value': np.float64(0.5)}, {'etiquette_dpe_ademe': 'C', 'sample_size': 274, 'paired_t_test_t_statistic': np.float64(-24.456129953714484), 'paired_t_test_p_value': np.float64(9.575278762137186e-71), 'wilcoxon_statistic': np.float64(1167.0), 'wilcoxon_p_value': np.float64(2.7062409312998785e-41)}, {'etiquette_dpe_ademe': 'D', 'sample_size': 203, 'paired_t_test_t_statistic': np.float64(-18.52575385017894), 'paired_t_test_p_value': np.float64(1.977187324243306e-45), 'wilcoxon_statistic': np.float64(1018.0), 'wilcoxon_p_value': np.float64(8.039019179976112e-29)}, {'etiquette_dpe_ademe': 'E', 'sample_size': 34, 'paired_t_test_t_statistic': np.float64(-5.633302426214085), 'paired_t_test_p_value': np.float64(2.843639844987568e-06), 'wilcoxon_statistic': np.float64(36.0), 'wilcoxon_p_value': np.float64(7.792012166263478e-06)}, {'etiquette_dpe_ademe': 'F', 'sample_size': 12, 'paired_t_test_t_statistic': np.float64(-5.305492965990286), 'paired_t_test_p_value': np.float64(0.0002502928166655573), 'wilcoxon_statistic': np.float64(0.0), 'wilcoxon_p_value': np.float64(0.00048828125)}, {'etiquette_dpe_ademe': 'G', 'sample_size': 1, 'paired_t_test_t_statistic': -99999, 'paired_t_test_p_value': -99999, 'wilcoxon_statistic': -99999, 'wilcoxon_p_value': -99999}]

12:13:01.472 | INFO    | Task run 'transform-make-statistical-metrics-0c4' - Statistical metrics computed for 7 DPE groups.

12:13:01.475 | INFO    | Task run 'transform-make-statistical-metrics-0c4' - Finished in state Completed()

12:13:01.501 | INFO    | Task run 'transform-save-tables-files-ce1' - Saving transformed data to parquet files in gold zone.

12:13:01.507 | INFO    | Task run 'transform-save-tables-files-ce1' - Saved adresses data to parquet file in gold zone.

12:13:01.522 | INFO    | Task run 'transform-save-tables-files-ce1' - Saved logements data to parquet file in gold zone.

12:13:01.524 | INFO    | Task run 'transform-save-tables-files-ce1' - Saved villes data to parquet file in gold zone.

12:13:01.528 | INFO    | Task run 'transform-save-tables-files-ce1' - Saved donnees_geocodage data to parquet file in gold zone.

12:13:01.530 | INFO    | Task run 'transform-save-tables-files-ce1' - Saved donnees_climatiques data to parquet file in gold zone.

12:13:01.533 | INFO    | Task run 'transform-save-tables-files-ce1' - Saved tests_statistiques_dpe data to parquet file in gold zone.

12:13:01.533 | INFO    | Task run 'transform-save-tables-files-ce1' - All data saved successfully in gold zone.

12:13:01.536 | INFO    | Task run 'transform-save-tables-files-ce1' - Finished in state Completed()

12:13:01.561 | INFO    | Flow run 'gainful-binturong' - Finished in state Completed()

In [15]:
pipeline_load = DataEnedisAdemeLoader(
    engine=obj_engine,
    debug=True)
pipeline_load.run()

Environment: LOCAL

12:13:10.440 | INFO    | Flow run 'burrowing-pogona' - Beginning flow run 'burrowing-pogona' for flow 'ETL data loading pipeline'

12:13:10.441 | INFO    | Flow run 'burrowing-pogona' - View at http://localhost:4200/runs/flow-run/cf8560ea-4ca1-4847-828f-6ba216bbcda3

12:13:10.457 | INFO    | Task run 'load-save-tables-to-db-8b7' - Colonne batch_id convertie en type str pour la table tests_statistiques_dpe.

12:13:10.459 | INFO    | Task run 'load-save-tables-to-db-8b7' - Colonne etiquette_dpe_ademe convertie en type str pour la table tests_statistiques_dpe.

12:13:10.707 | INFO    | Task run 'load-save-tables-to-db-8b7' - Nombre de lignes à insérer dans la table tests_statistiques_dpe: 7 lignes.

12:13:10.708 | INFO    | Task run 'load-save-tables-to-db-8b7' - Colonnes du DataFrame à insérer dans la table tests_statistiques_dpe: ['etiquette_dpe_ademe', 'sample_size', 'paired_t_test_t_statistic', 'paired_t_test_p_value', 'wilcoxon_statistic', 'wilcoxon_p_value', 'batch_id'].

12:13:10.742 | INFO    | Task run 'load-save-tables-to-db-8b7' - Données envoyées avec succès à la table tests_statistiques_dpe.

12:13:10.743 | INFO    | Task run 'load-save-tables-to-db-8b7' - Finished in state Completed()

12:13:10.763 | INFO    | Task run 'load-save-tables-to-db-43c' - Colonne id_ban convertie en type str pour la table adresses.

12:13:10.894 | INFO    | Task run 'load-save-tables-to-db-43c' - Nombre de lignes à insérer dans la table adresses: 75 lignes.

12:13:10.895 | INFO    | Task run 'load-save-tables-to-db-43c' - Colonnes du DataFrame à insérer dans la table adresses: ['id_ban', 'complement_d_adresse_batiment_ademe', 'label_ban', 'complement_d_adresse_logement_ademe', 'full_adress_ban'].

12:13:10.932 | INFO    | Task run 'load-save-tables-to-db-43c' - Données envoyées avec succès à la table adresses.

12:13:10.934 | INFO    | Task run 'load-save-tables-to-db-43c' - Finished in state Completed()

12:13:10.951 | INFO    | Task run 'load-save-tables-to-db-5f7' - Colonne code_postal_ban_ademe convertie en type str pour la table villes.

12:13:11.081 | INFO    | Task run 'load-save-tables-to-db-5f7' - Nombre de lignes à insérer dans la table villes: 18 lignes.

12:13:11.082 | INFO    | Task run 'load-save-tables-to-db-5f7' - Colonnes du DataFrame à insérer dans la table villes: ['city_ban', 'code_postal_ban_ademe', 'code_departement_enedis'].

12:13:11.116 | INFO    | Task run 'load-save-tables-to-db-5f7' - Données envoyées avec succès à la table villes.

12:13:11.118 | INFO    | Task run 'load-save-tables-to-db-5f7' - Finished in state Completed()

12:13:11.136 | INFO    | Task run 'load-save-tables-to-db-e67' - Colonne id_ban convertie en type str pour la table donnees_geocodage.

12:13:11.269 | INFO    | Task run 'load-save-tables-to-db-e67' - Nombre de lignes à insérer dans la table donnees_geocodage: 75 lignes.

12:13:11.270 | INFO    | Task run 'load-save-tables-to-db-e67' - Colonnes du DataFrame à insérer dans la table donnees_geocodage: ['score_ban_ademe', 'id_ban', 'lon_ban', 'statut_geocodage_ademe', 'lat_ban'].

12:13:11.309 | INFO    | Task run 'load-save-tables-to-db-e67' - Données envoyées avec succès à la table donnees_geocodage.

12:13:11.311 | INFO    | Task run 'load-save-tables-to-db-e67' - Finished in state Completed()

12:13:11.328 | INFO    | Task run 'load-save-tables-to-db-36f' - Colonne id_ban convertie en type str pour la table donnees_climatiques.

12:13:11.458 | INFO    | Task run 'load-save-tables-to-db-36f' - Nombre de lignes à insérer dans la table donnees_climatiques: 75 lignes.

12:13:11.462 | INFO    | Task run 'load-save-tables-to-db-36f' - Colonnes du DataFrame à insérer dans la table donnees_climatiques: ['id_ban', 'zone_climatique_ademe'].

12:13:11.499 | INFO    | Task run 'load-save-tables-to-db-36f' - Données envoyées avec succès à la table donnees_climatiques.

12:13:11.501 | INFO    | Task run 'load-save-tables-to-db-36f' - Finished in state Completed()

12:13:11.518 | INFO    | Task run 'load-save-tables-to-db-6ee' - Colonne _id_ademe convertie en type str pour la table logements.

12:13:12.059 | INFO    | Task run 'load-save-tables-to-db-6ee' - Nombre de lignes à insérer dans la table logements: 529 lignes.

12:13:12.060 | INFO    | Task run 'load-save-tables-to-db-6ee' - Colonnes du DataFrame à insérer dans la table logements: ['type_energie_generateur_n1_installation_n1_ademe', 'conso_5_usages_par_m2_ef_ademe', 'surface_habitable_desservie_par_installation_ecs_n1_ademe', 'deperditions_portes_ademe', 'emission_ges_ecs_ademe', 'volume_stockage_generateur_n1_ecs_n1_ademe', 'emission_ges_ecs_energie_n1_ademe', 'cout_total_5_usages_energie_n1_ademe', 'conso_5_usages_par_m2_ep_ademe', 'type_energie_principale_chauffage_ademe', 'numero_de_voie_enedis', 'ubat_w_par_m2_k_ademe', 'batch_id', 'surface_habitable_logement_ademe', 'type_energie_n1_ademe', 'consumption_difference', 'type_energie_n2_ademe', 'deperditions_ponts_thermiques_ademe', 'emission_ges_5_usages_par_m2_ademe', 'deperditions_murs_ademe', 'emission_ges_auxiliaires_ademe', 'periode_construction_ademe', 'absolute_diff_conso_fin_act', 'type_energie_generateur_n1_ecs_n1_ademe', 'type_energie_principale_ecs_ademe', 'type_installation_ecs_ademe', 'usage_generateur_n1_ecs_n1_ademe', 'deperditions_baies_vitrees_ademe', 'nombre_de_logements_enedis', 'conso_ef_generateur_n1_ecs_n1_ademe', 'etiquette_ges_ademe', 'apport_interne_saison_chauffe_ademe', 'apport_solaire_saison_chauffe_ademe', 'conso_kwh_m2', 'absolute_diff_conso_prim_fin', 'id_ban', 'cout_ecs_energie_n1_ademe', 'cout_total_5_usages_energie_n2_ademe', 'conso_chauffage_generateur_n1_installation_n1_ademe', 'emission_ges_chauffage_ademe', 'qualite_isolation_menuiseries_ademe', 'classe_inertie_batiment_ademe', 'annee_construction_ademe', 'etiquette_dpe_ademe', '_id_ademe', 'besoin_ecs_ademe', 'code_postal_ban_ademe'].

12:13:12.444 | INFO    | Task run 'load-save-tables-to-db-6ee' - Données envoyées avec succès à la table logements.

12:13:12.445 | INFO    | Task run 'load-save-tables-to-db-6ee' - Finished in state Completed()

12:13:12.446 | INFO    | Flow run 'burrowing-pogona' - Toutes les tables ont été envoyées avec succès à la base de données.

12:13:12.471 | INFO    | Flow run 'burrowing-pogona' - Finished in state Completed()

In [18]:
import pandas as pd


pd.read_sql("select * from dpedb_v1_domestic_remote.public.villes", con=obj_engine)

   code_postal_ban_ademe             city_ban code_departement_enedis
0                  95120               Ermont                      95
1                  53500                Ernée                      53
2                  59193       Erquinghem-Lys                      59
3                  22430                Erquy                      22
4                  54680           Errouville                      54
5                  77450                Esbly                      77
6                  31750           Escalquens                      31
7                  12500             Espalion                      12
8                  43000  Espaly-Saint-Marcel                      43
9                  54270      Essey-lès-Nancy                      54
10                 59940             Estaires                      59
11                 37320               Esvres                      37
12                 76260                   Eu                      76
13                 74140            Excenevex                      74
14                 24160            Excideuil                      24
15                 25400            Exincourt                      25
16                 38320               Eybens                      38
17                 87120           Eymoutiers                      87